backend = "glx";
vsync = true;
detect-client-opacity = true;
use-damage = true;
resize-damage = false;
use-ewmh-active-win = true;
detect-client-leader = true;
detect-transient = true;
dithered-present = true;

shadow = false;
fading = false;

corner-radius = 4;

blur-background = true;

blur: {
  method = "dual_kawase";
  strength = 8;
  background = true;
  background-frame = true;
  background-fixed = true;
}

rules = (
  {
    match = "window_type != 'dock' && window_type != 'desktop'";
    opacity = 0.90;
    blur-background = true;
  },
  {
    match = "fullscreen";
    opacity = 1.0;
  },
  {
    match = "class_g = 'steam_app_default' || class_g *= 'steam_app_'";
    opacity = 1.0;
    blur-background = false;
    corner-radius = 0;
  },
)